version: '3.8'

services:
  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/products"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    depends_on:
      product-service:
        condition: service_healthy
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

