version: '3.8'

services:
  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    # TODO: Přidejte healthcheck pro kontrolu stavu služby
    # healthcheck:
    #   test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8081/products"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    # TODO: Přidejte depends_on, aby se Order Service spustil až po Product Service
    # depends_on:
    #   - product-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge

